"""Init Gates.

Revision ID: bf11fc4de46d
Revises:
Create Date: 2024-03-06 10:08:16.239053
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf11fc4de46d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gate",
        sa.Column("station", sa.String(length=64), nullable=True),
        sa.Column(
            "state", sa.Enum("OPENED", "CLOSED", name="gatestate"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("station"),
    )
    with op.batch_alter_table("gate", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gate_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gate_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gate_updated_at"))
        batch_op.drop_index(batch_op.f("ix_gate_created_at"))

    op.drop_table("gate")
    op.execute("DROP TYPE gatestate")
    # ### end Alembic commands ###
