version: "3"
services:

  app:
    build: .
    command: ["local_entrypoint.sh"]
    container_name: 'headquarters-app'
    env_file: .env
    networks:
      - ns_network
    ports:
      - "8000:8000"
    stop_signal: SIGINT
    volumes:
      - ".:/app"

  tests:
    build: .
    command: ["pytest"]
    container_name: 'headquarters-tests'
    env_file: .env
    networks:
      - ns_network
    volumes:
      - ".:/app"

  celery:
    build: .
    command: ["entrypoint_celery.sh"]
    container_name: 'headquarters-celery'
    env_file: .env
    networks:
      - ns_network
    volumes:
      - ".:/app"

  redis:
    container_name: 'trains-broker'
    image: 'redis:7-alpine'
    networks:
      - ns_network
    ports:
      - "6379:6379"

  wdb:
    image: 'kozea/wdb:3.3.0'
    container_name: wdb
    deploy:
      resources:
        limits:
          memory: 1gb
    networks:
      - ns_network
    ports:
      - '1984:1984'

networks:
  ns_network:
    external: true